2025-03-16 14:34:00,939 - MainThread - WARNING - eduvpn.keyring - keyring.py:71 - error when checking if keyring is available: g-dbus-error-quark: The name is not activatable (2)
2025-03-16 14:34:00,940 - MainThread - WARNING - eduvpn.app - app.py:156 - Secure keyring not available, reverting to insecure file keyring!
2025-03-16 14:34:20,794 - MainThread - ERROR - eduvpn.nm - nm.py:665 - nm-device-error-quark: eduVPN failed to create resources: Failed to create WireGuard interface 'eduVPN' for 'eduVPN': Operation not supported (1)
2025-03-16 14:34:23,250 - call-model - WARNING - eduvpn.nm - nm.py:706 - no connection to deactivate of uuid <module 'uuid' from '/usr/lib/python3.13/uuid.py'>
2025-03-16 14:34:43,968 - MainThread - WARNING - eduvpn.keyring - keyring.py:71 - error when checking if keyring is available: g-dbus-error-quark: The name is not activatable (2)
2025-03-16 14:34:43,968 - MainThread - WARNING - eduvpn.app - app.py:156 - Secure keyring not available, reverting to insecure file keyring!
2025-03-16 14:34:52,603 - MainThread - ERROR - eduvpn.nm - nm.py:665 - nm-device-error-quark: eduVPN failed to create resources: Failed to create WireGuard interface 'eduVPN' for 'eduVPN': Operation not supported (1)
2025-03-16 14:41:58,067 - MainThread - WARNING - eduvpn.keyring - keyring.py:71 - error when checking if keyring is available: g-dbus-error-quark: The name is not activatable (2)
2025-03-16 14:41:58,067 - MainThread - WARNING - eduvpn.app - app.py:156 - Secure keyring not available, reverting to insecure file keyring!
2025-03-16 14:42:02,422 - MainThread - ERROR - eduvpn.nm - nm.py:665 - nm-device-error-quark: eduVPN failed to create resources: Failed to create WireGuard interface 'eduVPN' for 'eduVPN': Operation not supported (1)
2025-03-16 14:42:04,325 - call-model - WARNING - eduvpn.nm - nm.py:706 - no connection to deactivate of uuid <module 'uuid' from '/usr/lib/python3.13/uuid.py'>
2025-03-16 14:42:09,462 - MainThread - ERROR - /usr/lib/python3.13/site-packages/eduvpn/utils.py - utils.py:28 - Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/eduvpn/ui/ui.py", line 543, in copy_error_revealer
    self.eduvpn_app.enter_CopiedAnError()  # type: ignore
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/eduvpn/ui/app.py", line 114, in enter_CopiedAnError
    self.connection_notification.show(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        title=_("Error Copied"),
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        ),
        ^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/eduvpn/notify.py", line 29, in show
    self.notification.show()  # type: ignore
    ~~~~~~~~~~~~~~~~~~~~~~^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (2)
2025-03-16 14:59:12,189 - MainThread - WARNING - eduvpn.keyring - keyring.py:71 - error when checking if keyring is available: g-dbus-error-quark: The name is not activatable (2)
2025-03-16 14:59:12,190 - MainThread - WARNING - eduvpn.app - app.py:156 - Secure keyring not available, reverting to insecure file keyring!
2025-03-17 21:01:49,427 - MainThread - WARNING - eduvpn.keyring - keyring.py:71 - error when checking if keyring is available: g-dbus-error-quark: The name is not activatable (2)
2025-03-17 21:01:49,427 - MainThread - WARNING - eduvpn.app - app.py:156 - Secure keyring not available, reverting to insecure file keyring!
2025-03-18 09:57:07,348 - MainThread - WARNING - eduvpn.keyring - keyring.py:71 - error when checking if keyring is available: g-dbus-error-quark: The name is not activatable (2)
2025-03-18 09:57:07,348 - MainThread - WARNING - eduvpn.app - app.py:156 - Secure keyring not available, reverting to insecure file keyring!
